### PR TITLE
updated notepad++ files with current head versions

### PR DESCRIPTION
**Pull request by chcg**

### CODE REVIEW

**Comment by chcg** [comment]
@donho Isn't it time to update now as N++ 7.7 is out? I could update this PR if you like.

**Comment by donho** [comment]
What's the point of this PR ?

**Comment by donho** [comment]
OK, I see. Sure.

**Comment by donho** [comment]
@chcg have you compiled the code after being modified, and test it?
If it all works, please merge it.

**Comment by chcg** [comment]
@donho Updated this PR with a working version of the 7.7 header files. Plugin is still functional with the changes. VS project file updated to VS2015 should it be VS2017?

**Comment by donho** [comment]
Yes, VS2017 please.
Since Sintilla/boost's RegEx/Notepad++ are compiled under VS2017 now.

**Comment by chcg** [comment]
@donho Done, changed platform toolset to v141_xp.

**Comment by donho** [comment]
@chcg You can merge now, please.

**Comment by chcg** [comment]
@donho  I can't. For npp-plugins I don't have the access rights.

**Comment by donho** [comment]
https://github.com/npp-plugins/plugintemplate/commit/d2814d4bd9d96c475673e3a1902d318fb869059e

**Pull request closed without merging**
